import { Timestamp } from 'firebase/firestore';

const exampleTasks = [
 {
  archived: false,
  column: 'backlog-column',
  comments: [
   {
    authorId: 'fake-id',
    authorName: 'Maxim Buz',
    text: 'This is a comment. You can add one too, if you like!',
    timestamp: Timestamp.now(),
   },
   {
    authorId: 'fake-id',
    authorName: 'Maxim Buz',
    text: 'Just type in something and press enter :)',
    timestamp: Timestamp.now(),
   },
  ],
  description:
   "This task is currently in the backlog. You can easily drag and drop this task into the 'Selected for developmemt' column, if you wish to start wortking on it.",
  identifier: 'EXP',
  priority: 'low',
  status: 'Backlog',
  summary: 'This is an example task. Feel free to update it',
  timestamp: Timestamp.now(),
  title: 'Test the backlog column',
 },
 {
  archived: false,
  column: 'selected-for-development-column',
  comments: [],
  description:
   "This task was selected for development. Just drag and drop it into a different column to update it's status! ",
  identifier: 'EXP',
  priority: 'medium',
  status: 'Selected for development',
  summary: 'This is an example of a task that has been selected for development',
  timestamp: Timestamp.now(),
  title: 'Check this task out',
 },
 {
  archived: false,
  column: 'selected-for-development-column',
  comments: [],
  description: 'And this one is selected for development',
  identifier: 'EXP',
  priority: 'high',
  status: 'Selected for development',
  summary: 'Phu, so much to develop...',
  timestamp: Timestamp.now(),
  title: 'Very important task!',
 },
 {
  archived: false,
  column: 'selected-for-development-column',
  comments: [],
  description:
   "This task was selected for development. Just drag and drop it into a different column to update it's status! ",
  identifier: 'EXP',
  priority: 'low',
  status: 'Selected for development',
  summary: 'Another one!',
  timestamp: Timestamp.now(),
  title: 'Not so important task...',
 },
 {
  archived: false,
  column: 'in-review-column',
  comments: [],
  description:
   "This task seems to be in review. Drag and drop it into the completed column, if you feel like it doesn't belong here! ",
  identifier: 'EXP',
  priority: 'medium',
  status: 'In review',
  summary: 'Someone might need to check this task out',
  timestamp: Timestamp.now(),
  title: 'Test all the columns',
 },
 {
  archived: false,
  column: 'in-review-column',
  comments: [
   {
    authorId: 'fake-id',
    authorName: 'Maxim Buz',
    text: 'Try to delete this task',
    timestamp: Timestamp.now(),
   },
   {
    authorId: 'fake-id',
    authorName: 'Maxim Buz',
    text: 'Just click on the "delete" button above and you should be fine! :)',
    timestamp: Timestamp.now(),
   },
  ],
  description: 'I think you should check out the comments below',
  identifier: 'EXP',
  priority: 'medium',
  status: 'In review',
  summary: 'Can you delete a task?',
  timestamp: Timestamp.now(),
  title: 'Test deletion of tasks',
 },
 {
  archived: false,
  column: 'completed-column',
  comments: [
   {
    authorId: 'fake-id',
    authorName: 'Maxim Buz',
    text: 'Try to archive this task',
    timestamp: Timestamp.now(),
   },
   {
    authorId: 'fake-id',
    authorName: 'Maxim Buz',
    text: 'Just click on the "archive" button above and you should be fine! :)',
    timestamp: Timestamp.now(),
   },
  ],
  description: 'I think you should check out the comments below',
  identifier: 'EXP',
  priority: 'low',
  status: 'Completed',
  summary: 'Can you archive a task?',
  timestamp: Timestamp.now(),
  title: 'Test archivation of tasks',
 },
 {
  archived: false,
  column: 'in-progress-column',
  comments: [
   {
    authorId: 'fake-id',
    authorName: 'Maxim Buz',
    text: 'Try to search for tasks',
    timestamp: Timestamp.now(),
   },
   {
    authorId: 'fake-id',
    authorName: 'Maxim Buz',
    text:
     'Close this task, find the "Seach Tasks" input field and try to find the "not so important" task  :)',
    timestamp: Timestamp.now(),
   },
  ],
  description: 'I think you should check out the comments below',
  identifier: 'EXP',
  priority: 'low',
  status: 'Completed',
  summary: 'Can you search for a specific task?',
  timestamp: Timestamp.now(),
  title: 'Finding unimportant tasks',
 },
 {
  archived: false,
  column: 'in-progress-column',
  comments: [
   {
    authorId: 'fake-id',
    authorName: 'Maxim Buz',
    text: 'Try to edit the task. Do you know how?',
    timestamp: Timestamp.now(),
   },
   {
    authorId: 'fake-id',
    authorName: 'Maxim Buz',
    text: "Just click on whatever text you'd like to change, update it and hit enter! :)",
    timestamp: Timestamp.now(),
   },
  ],
  description: 'I think you should check out the comments below',
  identifier: 'EXP',
  priority: 'low',
  status: 'Completed',
  summary: 'Are you able to edit a task description?',
  timestamp: Timestamp.now(),
  title: 'Updating a task',
 },
];

export default exampleTasks;
